# example values
server:
  port: 8080

spring:
  datasource:
    username: root
    password: Kf,enbyrf332
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
    - url: https://nikoartgallery.com/
      name: NikoArtGallery
    - url: https://playback.ru/
      name: Playback
  errors:
    indexingNotStarted : "Индексация не запущена"
    indexingAlreadyStarted : "Индексация уже запущена"
    indexingStopped : "Индексация остановлена пользователем"
    pageOutOfBound : "Данная страница находится за пределами сайтов, указанных в конфигурационном файле"
    emptyQuery : "Задан пустой поисковый запрос"
    pageNotFound : "Указанная страница не найдена"
  extensions:
    - .jpg
    - .png
    - .ico
    - .JPG
    - .jpeg
    - '#'
    - '@'
    - '?'
    - .mp4
    - .php
    - .pdf
jsoup-settings:
    referrer : "http://www.google.com"
    userAgent : "Mozilla/5.0 (Windows; U; WindowsNT5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6"
