# example values
#trace: true
server:
  port: 8080

spring:
  datasource:
    username: root
    password: Kf,enbyrf332
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
        #enable_lazy_load_no_trans : true
        #generate_statistics : true
        order_inserts : true
    hibernate:
      ddl-auto: update
    show-sql: true
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
indexing-settings:
  sites:
    - url: https://www.svetlovka.ru/
      name: svetlovka.ru
    - url : https://www.dextra.ru/
      name: Dextra



errors-settings:
  errors:
    indexingNotStarted : "Индексация не запущена"
    indexingAlreadyStarted : "Индексация уже запущена"
    indexingStopped : "Индексация остановлена пользователем"
    pageOutOfBound : "Данная страница находится за пределами сайтов, указанных в конфигурационном файле"
    emptyQuery : "Задан пустой поисковый запрос"
    pageNotFound : "Указанная страница не найдена"
extensions-settings:
  extensions:
    - .jpg
    - .png
    - .ico
    - .JPG
    - .jpeg
    - '#'
    - '@'
    - '?'
    - .mp4
    - .php
    - .pdf
    - .PDF
    - .doc
    - .xlsx
    - .xls
    - .bmp
jsoup-settings:
    referrer : "http://www.google.com"
    userAgent : "Mozilla/5.0 (Windows; U; WindowsNT5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6"
logging:
  level:
    org:
      type:
        descriptor:
          sql:
            BasicBinder: trace


